[project]
name = "git-tb"
version = "0.1.0"
description = "Git toolbox"
authors = [
    {name = "Alejandro Visiedo",email = "learning.little.engineer.2025.1@gmail.com"}
]
license = {text = "APACHE-2"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml (>=6.0.2,<6.1.0)"
]

[dependency-groups]
dev = [
    "pytest (>=8.3.5,<8.4.0)",
    "black (>=25.1.0,<25.2.0)",
    "pylint (>=3.3.7,<3.4.0)",
    "pdoc3 (>=0.11.6,<0.12.0)",
    "pytest-cov (>=6.2.1,<6.3.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
